version: '3.8'
services:
  bot:
    build: .
    container_name: bot-jipaexpress
    volumes:
      - ./backend/.wwebjs_auth:/app/.wwebjs_auth
    restart: always
    ports:
      - "8000:8000"
